Removed parts of Javadocs that caused build warnings
DANS-KNAW/easy-split-multi-deposit pull request #37
Opened 2016-10-11 09:08 UTC by janvanmansum

No JIRA-issue.

The build displayed a lot of warnings because of links in the Javadocs it couldn't create. These links were references to the Java JRE javadocs, Apache commons, etc. I chose the easiest solution: delete those references.

2016-10-11 09:08 UTC, janvanmansum commented
@DANS-KNAW/easy for review.

2016-10-11 11:14 UTC, rvanheest requested changes
Funny, @lindareijnhoudt and I just ran into this too, this morning... See the 2 comments of mine below.

2016-10-11 11:14 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/package.scala
> -      * @throws IOException in case of an I/O error
I really like to have these `@throws` here to remind us all that these methods can throw. On the other hand, we could also choose to go the other route of wrapping it in `Try`, but that would require some more effort (maybe make a JIRA issue for that?).

2016-10-11 11:14 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/package.scala
> +    def copyFile(destDir: File): Unit = FileUtils.copyFile(file, destDir)
why add a return type here and not in all other functions?

2016-10-17 10:00 UTC, lindareijnhoudt commented on src/main/scala/nl/knaw/dans/easy/multideposit/package.scala
> -      * @throws IOException in case of an I/O error
i agree. it seems to be a scaladoc bug. i see two options: 
- add a -no-link-warnings to the scaladoc, 
- or remove the throws-clauses from the docs

@janvanmansum has opted for the second one. i've added throws annotations to keep the reference in the code

2016-10-17 10:02 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/package.scala
> -      * @throws IOException in case of an I/O error
I think the addition of the annotations makes it kind of equivalent to the original. So definitely 👍 for that!

2016-10-17 10:18 UTC, merged