Fix easy 1015 -Verify instructions.csv in the preconditions
DANS-KNAW/easy-split-multi-deposit pull request #42
Opened 2017-01-17 08:20 UTC by PaulBoon

fixes EASY-1015
Verify instructions.csv in the preconditions

#### When applied it will
* check that files that are mentioned in the instructions.csv file should exist in the multi-deposit-directory
* check some dataset metadata fields from the instructions.csv file

#### Where should the reviewer @DANS-KNAW/easy start?
AddFileMetadataToDeposit.checkPreconditions
AddDatasetMetadataToDeposit.checkPreconditions

#### How should this be manually tested?
Use the 'spacetravel' test resources to run the easy_split_multi_deposit on a test server, could be deasy. After building, but befo0re testing,  make sure you run ./deploy-role easy_split_multi_deposit!

Introduce potential problems by renaming a file or changing/removing some of the files mentioned in the instructions.csv. This should result in an error message pointing to the missing file. Also remove some required field for the creator or contributor, for instance the initials. After running also this should result in error messages pointing to the missing required values.

2017-01-17 09:03 UTC, rvanheest requested changes
Looks good already! Here are some comments and change requests.

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/Main.scala
> +      .foldLeft(ActionAndResult())((acc, cur) => acc += cur)
we rewrote this when I explained this to you, but we forgot to revert it... Please put this back to `_ += _`

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +    if (emptyVals.nonEmpty && emptyVals.size < keys.size) {
shouldn't this be `emptyVals.size != keys.size`? Not sure though...

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +   * Verifies whether all preconditions are met for this specific action.
Maybe explain which preconditions you're checking in this ScalaDoc?

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +   * Verifies whether all preconditions are met for this specific action.
Maybe explain which preconditions you're checking in this ScalaDoc?

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +    val inputDir = settings.multidepositDir;//multiDepositDir(settings, datasetID)
why this comment?

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +      .filter(fp => fp.nonEmpty)
use `.filterNot(_.isEmpty)` instead

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +      .filterNot(fp => {
1. put this on one line. code block is not needed here.
2. either use the `Path` API or use the `File` API. To check `exists` with the `Path` API, use `Files.exists`. See also https://docs.oracle.com/javase/tutorial/essential/io/legacy.html.

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +      Success(Unit)
Replace all `Success(Unit)` instances in this PR with `Success(())`: `Unit` is a type; `()` is its instance.

2017-01-17 09:03 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +  val (datasetID, dataset) = entry
I really like this addition! Maybe you could do the same in `AddDatasetMetadataToDeposit`?

2017-01-17 09:50 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +    if (emptyVals.nonEmpty && emptyVals.size < keys.size) {
It's the same because it cannot be bigger; emptyVals it's filtered from keys

2017-01-17 10:17 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +    val inputDir = settings.multidepositDir;//multiDepositDir(settings, datasetID)
Yes, I forgot to cleanup

2017-01-17 10:28 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +      .filter(fp => fp.nonEmpty)
Ok, your suggestion is simpler to read

2017-01-17 12:09 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +      .filterNot(fp => {
Ok, Files.exists(inputDirPath.resolve(fp)) looks better

2017-01-19 12:11 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +  val (datasetID, dataset) = entry
OK

2017-01-19 12:28 UTC, rvanheest approved these changes

2017-01-23 08:43 UTC, merged