EASY-1197 and EASY-1162
DANS-KNAW/easy-split-multi-deposit pull request #44
Opened 2017-02-06 09:50 UTC by rvanheest

fixes EASY-1197 and EASY 1162

#### When applied it will
* [x] make sure the dataset column does not contain any invalid characters. It only accepts alpha-numeric characters.
* [x] change the implementation for mime-type detection to use Tika instead. After some testing with aperture, the current implementation and others, I found that Tika gave the correct results to all our test cases. Rather than going with aperture, I therefore decided to go with Tika instead. Although @jo-pol found Tika to be rather unpredictable regarding encodings, I found it to do a great job on mime-type recognition. As a result of this change, I removed the current implementation with the `getContentTypeFor` and additional map and put Tika in its place.
* [x] fix a small bug in the parsing of the `instructions.csv` file
* [x] hereby I declare I have run `mvn clean install` before submitting this PR and made sure all license headers are in place

#### Where should the reviewer @DANS-KNAW/easy start?
* For the dataset column changes, start in `CreateOutputDepositDir`
* For the mime-type changes, start in `AddFileMetadataToDeposit`
* For the bugfix in the parser, see `MultiDepositParser`

2017-02-06 15:29 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +    conclusie: mag niet tegelijk DCX_RELATION_LINK en DCX_RELATION_TITLE hebben
This is Dutch, so you need to translate it

2017-02-06 15:46 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +    conclusie: mag niet tegelijk DCX_RELATION_LINK en DCX_RELATION_TITLE hebben
Changed that like 3 hours ago. Lol

2017-02-07 08:26 UTC, jo-pol commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +          .getOrElse(checkNotAll(row, rowVals, "DCX_RELATION_LINK", "DCX_RELATION_TITLE"))
Easier to read: {link, title} can not be defined both, a qualifier is only allowed if link or title are present

2017-02-07 08:26 UTC, jo-pol commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +      .map(outputFileMetadataFile(datasetID).writeXml(_))
what if the write fails?

2017-02-07 08:26 UTC, jo-pol commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/CreateOutputDepositDir.scala
> +      _ <- checkDirectoriesDoNotExist
I suppose you are going to add the covariances here too?

2017-02-07 08:26 UTC, jo-pol commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDepositSpec.scala
> +    inside(new AddDatasetMetadataToDeposit(1, (datasetID, dataset)).checkPreconditions) {
inside is new to me, what does it do?

2017-02-07 08:26 UTC, jo-pol commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDepositSpec.scala
> +        message shouldBe "Exactly one of the following columns must contain a value: [DCX_RELATION_LINK, DCX_RELATION_TITLE]"
With the rewording above this might need rewording too.

2017-02-07 08:26 UTC, jo-pol commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDepositSpec.scala
> +        message shouldBe "Only a subset of the following columns must contain a value: [DCX_RELATION_LINK, DCX_RELATION_TITLE]"
Seems like you are trying to be too generic here. "one of" would be easier to read. What other cases do you have in mind to be covered by the same check and do they actually occur?

2017-02-07 08:26 UTC, jo-pol commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDepositSpec.scala
> +  it should "succeed with no relation qualifier and only a title" in {
with no -> without a

2017-02-07 08:26 UTC, jo-pol commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDepositSpec.scala
> +  it should "fail with no relation qualifier, link or title" in {
idem

2017-02-07 08:26 UTC, jo-pol commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDepositSpec.scala
> +      case Success(xml) => xml.child.map(Utility.trim) should (
Don't understand the purpose of this change. Looks only more complex to understand to me.

2017-02-07 08:58 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +    conclusie: mag niet tegelijk DCX_RELATION_LINK en DCX_RELATION_TITLE hebben
After some thought, I brought back the truth table. Seems to be a good addition as documentation.

2017-02-07 09:01 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDeposit.scala
> +      .map(outputFileMetadataFile(datasetID).writeXml(_))
the `writeXml` is inside a `map` on the `Try` class. The methods on this class are all fail safe using try-catch blocks. So if `writeXml` fails, the exception that is thrown will be caught by the surrounding `map` and cause the result to be a `Failure`.

2017-02-07 09:04 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/CreateOutputDepositDir.scala
> +      _ <- checkDirectoriesDoNotExist
Not sure what you're talking about. You mean [this kind of co/contravariance](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science))? More explanation please!

2017-02-07 09:04 UTC, rvanheest commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDepositSpec.scala
> +    inside(new AddDatasetMetadataToDeposit(1, (datasetID, dataset)).checkPreconditions) {
http://www.scalatest.org/user_guide/other_goodies#inside

2017-02-07 09:08 UTC, rvanheest commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDepositSpec.scala
> +        message shouldBe "Exactly one of the following columns must contain a value: [DCX_RELATION_LINK, DCX_RELATION_TITLE]"
what about

> The columns [DCX_RELATION_LINK, DCX_RELATION_TITLE] must not all contain a value at the same time

2017-02-07 09:12 UTC, rvanheest commented on src/test/scala/nl/knaw/dans/easy/multideposit/actions/AddFileMetadataToDepositSpec.scala
> +      case Success(xml) => xml.child.map(Utility.trim) should (
The return type of `datasetToFileXml` changed from `Elem` to `Try[Elem]`. That's why I had to make this change.

2017-02-07 10:14 UTC, rvanheest commented
ready for review/merge

2017-02-08 14:52 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddBagToDeposit.scala
> +case class AddBagToDeposit(row: Int, datasetID: DatasetID, dataset: Dataset)(implicit settings: Settings) extends Action {
I liked the entry: (DatasetID, Dataset), which is used by the other Actions. 
Could you use it here too?

2017-02-08 14:58 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/MultiDepositParser.scala
> +          })
Maybe this block should become  a function, because these nested for comprehensions look complicated

2017-02-08 15:02 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/MultiDepositParser.scala
>            // +2 because we want the second line (element 0) to have index 2
Maybe say 'the second line in the cvs file', hinting that we want a line number

2017-02-08 15:05 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddBagToDeposit.scala
> +    defaultCompleter.setTagManifestAlgorithm(algorithm)
Now it's not default anymore, so better not call it defaultCompleter

2017-02-08 15:10 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddBagToDeposit.scala
> +      .map(DateTime.parse)
What happens if paring fails, I don't see no Try's

2017-02-08 15:18 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +object validators {
Nice

2017-02-08 15:22 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +  def checkAllOrNone(row: Int, map: mutable.HashMap[MultiDepositKey, String], keys: String*): Try[Unit] = {
Maybe we can use a type for mutable.HashMap[MultiDepositKey, String],
 it's almost a 'Dataset'...?

2017-02-08 15:29 UTC, PaulBoon commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/CreateOutputDepositDir.scala
> +      _ <- checkDirectoriesDoNotExist
Maybe Joke refers to the files that are mentioned but do not exist; see checkPreconditions of AddFileMetadataToDeposit ?

2017-02-08 15:32 UTC, PaulBoon commented on src/test/resources/mimetypes/README.md
> +The files in this folder are ment to be test-cases for the mimetype detection that
'meant to be'

2017-02-09 08:04 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddBagToDeposit.scala
> +      .map(DateTime.parse)
Good point! The exception would have been caught eventually in the `createBag` function, but that is a little late to find that the date isn't formatted properly. Instead I added an extra check to `AddDatasetMetadataToDeposit` to validate that the date is formatted properly.

2017-02-09 08:11 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +  def checkAllOrNone(row: Int, map: mutable.HashMap[MultiDepositKey, String], keys: String*): Try[Unit] = {
Yup, it represents a **ROW** in the dataset. therefore I created a type alias called `DatasetRow` and changed all occurrences of `mutable.HashMap[MultiDepositKey, String]` to that.

2017-02-09 08:13 UTC, rvanheest commented
Thanks @PaulBoon for your detailed review! I did a commit for each of the comments, so reviews of these new changes can easily be tracked.

2017-02-09 09:55 UTC, rvanheest commented
Also the springfield things have been added to this PR.
@DANS-KNAW/easy please review

2017-02-09 14:47 UTC, lindareijnhoudt requested changes
these are all related to EASY-1169

2017-02-09 14:47 UTC, lindareijnhoudt commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +        <ddm:relation scheme="STREAMING_SURROGATE_RELATION">{path}</ddm:relation>
the STREAMING_SURROGATE_RELATION has the presentation as the final variable. this is not yet present during this stage, so it should be a placeholder

2017-02-09 14:47 UTC, lindareijnhoudt commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +        <ddm:relation scheme="STREAMING_SURROGATE_RELATION">{path}</ddm:relation>
doesn't the scheme-attribute need a namespace as well?

2017-02-09 14:47 UTC, lindareijnhoudt commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +      checkColumnsHaveAtMostOneRowWithValues(row, dataset, "SF_DOMAIN", "SF_USER", "SF_COLLECTION", "SF_PRESENTATION")
SF_PRESENTATION is not yet defined at this stage. (maybe it should not even be present?)

2017-02-09 15:31 UTC, lindareijnhoudt commented on src/main/scala/nl/knaw/dans/easy/multideposit/actions/AddDatasetMetadataToDeposit.scala
> +        <ddm:relation scheme="STREAMING_SURROGATE_RELATION">{path}</ddm:relation>
nope, the scheme attribute is in the xml-namespace itself

2017-02-09 15:36 UTC, lindareijnhoudt approved these changes

2017-02-09 15:58 UTC, merged